### ISSUE TITLE
Create and color the new labels used by the autolabeler probot

### ISSUE THREAD

**Issue by mithro** [verilog-to-routing/vtr-verilog-to-routing#306]
In https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/305 we merged a config file for the Probot Autolabeler bot. However, the config references some labels that don't exist;

```yaml
# Tools
ABC:            ["abc_with_bb_support"]
ACE2:           ["ace2"]
blifexplorer:   ["blifexplorer"]
Odin:           ["ODIN_II", "odin2_helper"]
VPR:            ["vpr"]
VTR Flow:       ["vtr_flow"]

# Libraries
libarchfpga:    ["libs/libarchfpga"]
libeasygl:      ["libs/libeasygl"]
liblog:         ["libs/liblog"]
libpugiutil:    ["libs/libpugiutil"]
libvtrutil:     ["libs/libvtrutil"]

# General areas
type-docs:      ["docs/", "README.md", "*.md", "tutorial", "README", "*.rst"]
type-infra:     [".travis.yml", ".travis.yml", ".travis/", "scripts/", ".github/", "Dockerfile"]
type-build:     ["Makefile", "*.make", "CMakeLists.txt", "cmake"]
type-tests:     ["*_test.pl", "*test*", "*TESTS*"]
type-external:  ["libs/EXTERNAL"]
type-scripts:   ["scripts", "*.pl", "*.sh"]

# Tag pull requests with the languages used to make it easy to see what is
# being used.
lang-hdl:       ["*.v", "*.sv"]
lang-cpp:       ["*.c*", "*.h"]
lang-perl:      ["*.pl", "*perl*"]
lang-python:    ["*.py"]
lang-shell:     ["*.sh"]
lang-netlist:   ["*.blif", "*.eblif", "*.edif"]
lang-make:      ["*.make", "Makefile", "CMakeLists.txt"]
```

The bot will happily create these labels, but it won't assign nice colors to them. We will have to do that manually.

I suggest that we color all the `lang-XXXX` labels the same color and all the `type-XXXX` another color. Keeping unique colors for the projects is probably fine.
